package GUI;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class AdminDashboard {
    private static JFrame FrameAdmin;
    private JPanel panel1;
    private JPanel topPanel;
    private JLabel welcomeText;
    private JPanel btnsPanel;
    private JButton btnAggiungiVolo;
    private JButton btnAreaPersonale;
    private JButton btnViewVoli;
    private JButton btnLogout;

    public static void main(String[] args) {
        FrameAdmin = new JFrame("Dashboard Admin");
        FrameAdmin.setContentPane(new AdminDashboard().panel1);
        FrameAdmin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        FrameAdmin.pack();
        FrameAdmin.setLocationRelativeTo(null);         // Centra la finestra sullo schermo
        FrameAdmin.setVisible(true);

        // Momentaneo in via precauzionale
        FrameAdmin.setResizable(false);

    }

    public AdminDashboard() {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.setMaximumSize(new Dimension(1000, 675));
        panel1.setMinimumSize(new Dimension(1000, 675));
        panel1.setPreferredSize(new Dimension(1000, 675));
        topPanel = new JPanel();
        topPanel.setLayout(new BorderLayout(5, 5));
        Font topPanelFont = this.$$$getFont$$$("Droid Sans Mono", Font.BOLD, 36, topPanel.getFont());
        if (topPanelFont != null) topPanel.setFont(topPanelFont);
        topPanel.setMaximumSize(new Dimension(1000, 150));
        topPanel.setMinimumSize(new Dimension(1000, 150));
        topPanel.setPreferredSize(new Dimension(1000, 150));
        panel1.add(topPanel);
        welcomeText = new JLabel();
        Font welcomeTextFont = this.$$$getFont$$$("Droid Sans Mono", Font.BOLD, 36, welcomeText.getFont());
        if (welcomeTextFont != null) welcomeText.setFont(welcomeTextFont);
        welcomeText.setHorizontalAlignment(0);
        welcomeText.setHorizontalTextPosition(0);
        welcomeText.setText("Bentornato, Admin!");
        welcomeText.setVerticalAlignment(3);
        welcomeText.setVerticalTextPosition(3);
        topPanel.add(welcomeText, BorderLayout.CENTER);
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Droid Sans Mono", Font.PLAIN, 18, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setHorizontalAlignment(0);
        label1.setHorizontalTextPosition(0);
        label1.setText("Cosa desideri fare oggi?");
        topPanel.add(label1, BorderLayout.SOUTH);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel2.setMaximumSize(new Dimension(1000, 20));
        panel2.setMinimumSize(new Dimension(1000, 20));
        panel2.setPreferredSize(new Dimension(1000, 20));
        panel1.add(panel2);
        btnsPanel = new JPanel();
        btnsPanel.setLayout(new BorderLayout(0, 0));
        btnsPanel.setMaximumSize(new Dimension(1000, 270));
        btnsPanel.setMinimumSize(new Dimension(1000, 270));
        btnsPanel.setPreferredSize(new Dimension(1000, 270));
        panel1.add(btnsPanel);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        panel3.setMinimumSize(new Dimension(500, 200));
        panel3.setPreferredSize(new Dimension(500, 250));
        btnsPanel.add(panel3, BorderLayout.WEST);
        btnAggiungiVolo = new JButton();
        btnAggiungiVolo.setHorizontalTextPosition(0);
        btnAggiungiVolo.setText("Button");
        panel3.add(btnAggiungiVolo, BorderLayout.NORTH);
        btnAreaPersonale = new JButton();
        btnAreaPersonale.setText("Button");
        panel3.add(btnAreaPersonale, BorderLayout.CENTER);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        panel4.setMinimumSize(new Dimension(500, 200));
        panel4.setPreferredSize(new Dimension(500, 250));
        btnsPanel.add(panel4, BorderLayout.CENTER);
        btnViewVoli = new JButton();
        Font btnVoliFont = this.$$$getFont$$$("Droid Sans Mono", Font.PLAIN, 14, btnViewVoli.getFont());
        if (btnVoliFont != null) btnViewVoli.setFont(btnVoliFont);
        btnViewVoli.setHorizontalTextPosition(0);
        btnViewVoli.setText("Voli");
        panel4.add(btnViewVoli, BorderLayout.NORTH);
        btnLogout = new JButton();
        Font btnLogoutFont = this.$$$getFont$$$("Droid Sans Mono", Font.PLAIN, 14, btnLogout.getFont());
        if (btnLogoutFont != null) btnLogout.setFont(btnLogoutFont);
        btnLogout.setText("Logout");
        panel4.add(btnLogout, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
