package GUI;

import controller.Controller;

import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class LandingPageLogin {
    private JPanel mainPanel;
    private static JFrame FrameLogin;
    private Controller controller;

    public static void main(String[] args) {
        FrameLogin = new JFrame("Login");
        FrameLogin.setContentPane(new LandingPageLogin().mainPanel);
        FrameLogin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        FrameLogin.pack();
        FrameLogin.setVisible(true);

    }

    public LandingPageLogin() {
        controller = new Controller();

        // ADD ACTION LISTENERS OR OTHER CODE
    }






    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
